In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Used_Bikes.csv")

In [4]:
df.info()
df.drop_duplicates(inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [5]:
df.value_counts()

bike_name                    price      city       kms_driven  owner        age   power  brand
BMW F750 GS 850cc            1350000.0  Delhi      4600.0      First Owner  3.0   850.0  BMW              1
Royal Enfield Classic 350cc  75000.0    Pune       23045.0     First Owner  9.0   350.0  Royal Enfield    1
                                        Delhi      29716.0     First Owner  11.0  350.0  Royal Enfield    1
                                                   20000.0     First Owner  9.0   350.0  Royal Enfield    1
                             74000.0    Mumbai     15000.0     First Owner  9.0   350.0  Royal Enfield    1
                                                                                                         ..
Hero HF Deluxe 100cc         18000.0    Faridabad  13290.0     First Owner  9.0   100.0  Hero             1
                             14500.0    Faridabad  17604.0     First Owner  12.0  100.0  Hero             1
Hero HF Deluxe 100 cc        30000.0    Jaipur     40457.0     First Owner  7.0   100.0  Hero             1
Hero HF Dawn 100cc           32500.0    Delhi      12045.0     First Owner  5.0   100.0  Hero             1
Yezdi Classic 250cc          68000.0    Ahmedabad  23.0        Third Owner  39.0  250.0  Yezdi            1
Name: count, Length: 7324, dtype: int64

In [6]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [7]:
catgorical = df.select_dtypes(include="O")
catgorical.head(200)

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
210,Bajaj Pulsar 180cc,Delhi,First Owner,Bajaj
211,Yamaha YZF-R15 V3 150cc,Delhi,First Owner,Yamaha
212,Bajaj Platina 100cc,Delhi,First Owner,Bajaj
213,TVS Apache RTR 200 4V FI,Delhi,First Owner,TVS
214,Royal Enfield Bullet Twinspark 350cc,Delhi,First Owner,Royal Enfield

In [8]:
catgorical["owner"].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [9]:
num = df.select_dtypes(exclude="O")
num.head()

      price  kms_driven  age  power
0   35000.0     17654.0  3.0  110.0
1  119900.0     11000.0  4.0  350.0
2  600000.0       110.0  8.0  675.0
3   65000.0     16329.0  4.0  180.0
4   80000.0     10000.0  3.0  150.0

In [10]:
df["brand"].value_counts().keys()

Index(['Bajaj', 'Royal Enfield', 'Hero', 'Honda', 'Yamaha', 'TVS', 'KTM',
       'Suzuki', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Mahindra',
       'Benelli', 'Triumph', 'Ducati', 'BMW', 'Jawa', 'Indian', 'MV',
       'Rajdoot', 'LML', 'Yezdi', 'Ideal'],
      dtype='object', name='brand')

In [11]:
brand_list = ['Bajaj', 'Hero', 'Royal Enfield', 'Yamaha', 'Honda', 'Suzuki', 'TVS',
       'KTM', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Benelli', 'Mahindra',
       'Triumph', 'Ducati', 'BMW', 'Jawa', 'MV', 'Indian', 'Ideal', 'Rajdoot',
       'LML', 'Yezdi']

In [12]:
#catgorical = df[df["brand"].isin(brand_list)]
#catgorical.head()
catgorical["owner"]

0       First Owner
1       First Owner
2       First Owner
3       First Owner
4       First Owner
           ...
9362    First Owner
9369    First Owner
9370    First Owner
9371    First Owner
9372    First Owner
Name: owner, Length: 7324, dtype: object

In [13]:
dt1 = {"First Owner":1,"Second Owner":2,"Third Owner":3,"Fourth Owner Or More":4}
df["owner"] = df["owner"].map(dt1)

In [14]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [15]:
catgorical[catgorical["owner"] == 4]

Empty DataFrame
Columns: [bike_name, city, owner, brand]
Index: []

In [16]:
brand_list

['Bajaj',
 'Hero',
 'Royal Enfield',
 'Yamaha',
 'Honda',
 'Suzuki',
 'TVS',
 'KTM',
 'Harley-Davidson',
 'Kawasaki',
 'Hyosung',
 'Benelli',
 'Mahindra',
 'Triumph',
 'Ducati',
 'BMW',
 'Jawa',
 'MV',
 'Indian',
 'Ideal',
 'Rajdoot',
 'LML',
 'Yezdi']

In [17]:
brand_list
dt = {"Bajaj":1,"Royal Enfield":2}

dt= {}
for i in range(1,len(brand_list)):
    dt[brand_list[i]] = i
dt

{'Hero': 1,
 'Royal Enfield': 2,
 'Yamaha': 3,
 'Honda': 4,
 'Suzuki': 5,
 'TVS': 6,
 'KTM': 7,
 'Harley-Davidson': 8,
 'Kawasaki': 9,
 'Hyosung': 10,
 'Benelli': 11,
 'Mahindra': 12,
 'Triumph': 13,
 'Ducati': 14,
 'BMW': 15,
 'Jawa': 16,
 'MV': 17,
 'Indian': 18,
 'Ideal': 19,
 'Rajdoot': 20,
 'LML': 21,
 'Yezdi': 22}

In [18]:
dt = {item: i for i, item in enumerate(brand_list,start=1)}
dt

{'Bajaj': 1,
 'Hero': 2,
 'Royal Enfield': 3,
 'Yamaha': 4,
 'Honda': 5,
 'Suzuki': 6,
 'TVS': 7,
 'KTM': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Benelli': 12,
 'Mahindra': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16,
 'Jawa': 17,
 'MV': 18,
 'Indian': 19,
 'Ideal': 20,
 'Rajdoot': 21,
 'LML': 22,
 'Yezdi': 23}

In [19]:
df["brand"] = df["brand"].map(dt)

In [20]:
x = df.drop(["bike_name","price","city"],axis="columns")

In [21]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      7
1        11000.0      1  4.0  350.0      3
2          110.0      1  8.0  675.0     14
3        16329.0      1  4.0  180.0      7
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      2
9369     60000.0      1  9.0  220.0      1
9370      3430.0      1  4.0  750.0      9
9371     21300.0      1  4.0  400.0      1
9372      7127.0      1  5.0  220.0      1

[7324 rows x 5 columns]

In [22]:
x.isnull().sum()

kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [23]:
catgorical.drop(["bike_name","city"],axis="columns",inplace=True)
catgorical

            owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [24]:
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [25]:
catgorical["owner"].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [26]:
catgorical

            owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [27]:
y = df[["price"]]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [30]:
x_train

      kms_driven  owner   age  power  brand
5261     51528.0      1   9.0  150.0      2
4859     24000.0      1   9.0  150.0      4
45       35000.0      1   9.0  200.0      1
8239     27598.0      1   8.0  110.0      5
9212     55000.0      1  14.0  150.0      2
...          ...    ...   ...    ...    ...
7585     18000.0      1   6.0  125.0      2
1286     14751.0      1   4.0  125.0      5
2186     25754.0      1   7.0  390.0      8
1235     19000.0      1   4.0  100.0      2
420      16000.0      1   4.0  220.0      1

[5859 rows x 5 columns]

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lg = LinearRegression()

In [33]:
# Algorithm training
lg.fit(x_train,y_train)   #training data for the training purpose

LinearRegression()

In [34]:
print("Training score : ",round(lg.score(x_train,y_train)*100,2))
print("Testing score : ",round(lg.score(x_test,y_test)*100,2))

Training score :  71.0
Testing score :  73.06

In [35]:
prediction = lg.predict(x_test)
prediction

array([[ 38225.44082055],
       [161877.97246871],
       [ 48523.26424396],
       ...,
       [116902.94606687],
       [ 44652.12541614],
       [  2715.6684546 ]])

In [36]:
y_hat=lg.predict(x_test)

In [37]:
y_test['prediction']=y_hat

In [38]:
y_test['prediction']=y_test['prediction'].map(lambda x:round(x,2))

In [39]:
y_test.head(40)

         price  prediction
8186   25000.0    38225.44
350   118000.0   161877.97
6520   80000.0    48523.26
7998   52000.0    65180.10
16    120000.0    54396.54
6142   20999.0    -4757.28
2453  125000.0   222729.69
2069   70000.0    61127.22
1434   64999.0   108107.49
5254   65000.0    35052.72
2545  220500.0   218366.78
3485   36000.0    48998.55
2883   26000.0    42905.87
6263   70000.0    59801.55
2136   35000.0    -3738.43
7346   43000.0    44272.85
2830  110000.0   228249.33
2049  130000.0   155817.21
4723   23500.0    35660.08
2128  599999.0   496374.77
7569   23490.0    -4130.64
1514   76000.0    98849.54
4051   28000.0    44440.94
2582   13000.0   -24265.03
4377   28000.0     4203.04
1619  450000.0   424958.91
8002  100300.0   147700.11
562    26900.0    27610.50
3272   65000.0    47573.42
9246   30000.0    11736.40
1185   65000.0    99778.29
7021   66000.0    64899.84
5245   97500.0   143928.91
8213  110000.0   156360.45
6891   30200.0    -3759.53
3484   36000.0     8046.11
2057   40000.0    48757.81
3008   50000.0    22537.98
9284  115800.0   114225.87
5534   65000.0   106163.43

In [40]:
y_test

         price  prediction
8186   25000.0    38225.44
350   118000.0   161877.97
6520   80000.0    48523.26
7998   52000.0    65180.10
16    120000.0    54396.54
...        ...         ...
2348   36000.0     9379.85
9195   70000.0   105571.92
711   110000.0   116902.95
2490   35000.0    44652.13
8269   38000.0     2715.67

[1465 rows x 2 columns]

In [41]:
import joblib

In [42]:
#joblib.dump(ls,"favourate_student.lb")

In [43]:
#ls = ["arushi","kratika","neetesh","kartike","nikita rawat"]

In [44]:
#favourate_student = joblib.load("favourate_student.lb")
#favourate_student

In [45]:
#joblib.dump(lg,"LinearRegression.lb")

In [46]:
x_train

      kms_driven  owner   age  power  brand
5261     51528.0      1   9.0  150.0      2
4859     24000.0      1   9.0  150.0      4
45       35000.0      1   9.0  200.0      1
8239     27598.0      1   8.0  110.0      5
9212     55000.0      1  14.0  150.0      2
...          ...    ...   ...    ...    ...
7585     18000.0      1   6.0  125.0      2
1286     14751.0      1   4.0  125.0      5
2186     25754.0      1   7.0  390.0      8
1235     19000.0      1   4.0  100.0      2
420      16000.0      1   4.0  220.0      1

[5859 rows x 5 columns]